export const allServicesData = {
  // ── Main Category 1: Software ──
  'software': {
    title: 'Software & Tech Solutions',
    tagline: 'Digital Solutions Designed Around Your Business',
    category: 'Software',
    parentSlug: null,
    heroBg: 'bg-gradient-to-br from-indigo-950 via-slate-900 to-black text-white',
    description: "Every business is unique. That's why we build technology specifically for your workflow instead of forcing your business to adapt to generic software. From custom ERPs and CRMs to modern web platforms, mobile apps, and business intelligence.",
    features: [
      'Custom ERP and CRM development',
      'High-performance web applications and corporate portals',
      'Android, iOS and cross-platform mobile apps',
      'Real-time business intelligence and telemetry dashboards',
    ],
    subServices: [
      { slug: 'custom-software', title: 'Custom Software Development', desc: 'ERP, CRM, and bespoke workflow automation engines.' },
      { slug: 'web-development', title: 'Web Development', desc: 'Corporate websites, e-commerce platforms, customer portals.' },
      { slug: 'mobile-apps', title: 'Mobile App Development', desc: 'Native and cross-platform Android and iOS applications.' },
      { slug: 'business-intelligence', title: 'Business Intelligence & Dashboards', desc: 'Interactive KPI dashboards, automated reporting, analytics.' },
    ],
    industries: ['Manufacturing', 'Healthcare', 'Education', 'Retail', 'Logistics', 'Startups', 'SMEs', 'Enterprises'],
  },

  'software/custom-software': {
    title: 'Custom Software Development',
    tagline: 'Tailor-Made Software Built for Operational Excellence',
    category: 'Software',
    parentSlug: 'software',
    parentTitle: 'Software & Tech Solutions',
    heroBg: 'bg-gradient-to-br from-blue-950 via-slate-900 to-black text-white',
    description: 'We architect bespoke software systems designed around your exact business processes. Eliminate licensing overhead, bypass generic SaaS limitations, and own your software completely.',
    features: [
      'ERP Solutions: Complete Enterprise Resource Planning for manufacturing, retail, logistics, and education',
      'CRM Solutions: Lead management, automated sales pipelines, customer ticketing, and interaction history',
      'Inventory & Warehouse Management: Real-time stock tracking, barcode integrations, and dispatch control',
      'Workflow Automation Engines: Reduce human bottlenecks with automated document flows and approval chains',
    ],
    deliverables: [
      'Custom database design and optimization (PostgreSQL / MySQL / MongoDB)',
      'Secure multi-role authentication and RBAC permissions',
      'RESTful & GraphQL API integrations with legacy software',
      'Complete intellectual property and source code handover',
    ],
    industries: ['Manufacturing', 'Retail & Distribution', 'Healthcare', 'Logistics & Supply Chain', 'Education'],
  },

  'software/web-development': {
    title: 'Web Development & Platforms',
    tagline: 'High-Performance, SEO-Optimized Web Architecture',
    category: 'Software',
    parentSlug: 'software',
    parentTitle: 'Software & Tech Solutions',
    heroBg: 'bg-gradient-to-br from-cyan-950 via-slate-900 to-black text-white',
    description: 'From conversion-focused corporate websites to scalable web applications and customer portals. We build fast, responsive, and SEO-engineered web platforms using React, Next.js, and modern cloud infrastructures.',
    features: [
      'Corporate & Brand Websites: High-converting, lightning-fast digital storefronts',
      'E-Commerce Platforms: Custom product catalogs, cart, checkout, and payment gateways',
      'Customer & Vendor Portals: Secure client dashboards with self-service capabilities',
      'Web Applications: Interactive tools, booking engines, and internal admin panels',
    ],
    deliverables: [
      '100% responsive desktop, tablet, and mobile interface design',
      'Sub-second page load times with Core Web Vitals optimization',
      'Structured JSON-LD schema markup for AEO and Google Rich Snippets',
      'Admin CMS panels for seamless in-house content updates',
    ],
    industries: ['Startups & Scaleups', 'B2B Enterprises', 'E-Commerce Brands', 'Professional Services', 'Institutions'],
  },

  'software/mobile-apps': {
    title: 'Mobile App Development',
    tagline: 'Native & Cross-Platform Mobile Experiences',
    category: 'Software',
    parentSlug: 'software',
    parentTitle: 'Software & Tech Solutions',
    heroBg: 'bg-gradient-to-br from-indigo-950 via-slate-900 to-black text-white',
    description: 'We develop intuitive, high-performance mobile applications for Android and iOS that connect users with your products, IoT hardware, and business services.',
    features: [
      'Android App Development: Native Kotlin and Java implementations',
      'iOS App Development: Native Swift architectures for Apple ecosystem',
      'Cross-Platform Apps: React Native and Flutter for unified multi-platform codebases',
      'Hardware Companion Apps: Bluetooth Low Energy (BLE) and Wi-Fi IoT device control',
    ],
    deliverables: [
      'App Store and Google Play Store submission and compliance',
      'Offline-first synchronization with local caching',
      'Push notification pipelines and background task handling',
      'Biometric authentication and secure local storage',
    ],
    industries: ['IoT & Connected Hardware', 'Consumer Services', 'Healthcare', 'Field Operations', 'Retail'],
  },

  'software/business-intelligence': {
    title: 'Business Intelligence & Dashboards',
    tagline: 'Transform Raw Data into Decisive Operational Action',
    category: 'Software',
    parentSlug: 'software',
    parentTitle: 'Software & Tech Solutions',
    heroBg: 'bg-gradient-to-br from-slate-950 via-neutral-900 to-black text-white',
    description: 'Interactive analytics, telemetry visualizations, KPI trackers, and automated reporting systems that help executives and engineers make data-driven decisions.',
    features: [
      'Interactive KPI Dashboards: Real-time visual tracking of key business metrics',
      'IoT Telemetry Dashboards: Live sensor streaming, anomaly detection, and fault alerts',
      'Automated Reporting Tools: Scheduled PDF and Excel generation delivered to stakeholders',
      'Predictive Analytics: Trend analysis and operational forecasting models',
    ],
    deliverables: [
      'Custom visualization charts, heatmaps, and geospatial mapping',
      'Role-based access controls for sensitive financial and operational metrics',
      'High-throughput data ingestion pipelines',
      'Exportable audit trails and compliance logging',
    ],
    industries: ['Manufacturing', 'Energy & Utilities', 'Executive Management', 'Logistics', 'Retail Operations'],
  },

  // ── Main Category 2: Hardware ──
  'hardware': {
    title: 'Hardware Design & Embedded Systems',
    tagline: 'Turning Electronic Ideas into Real Products',
    category: 'Hardware',
    parentSlug: null,
    heroBg: 'bg-gradient-to-br from-emerald-950 via-slate-900 to-black text-white',
    description: 'CoreForge specializes in complete electronic product development: from concept and schematic design to PCB manufacturing support, RTOS, and embedded firmware.',
    features: [
      'Electronics product design and circuit architecture',
      'Multi-layer and high-speed PCB design services',
      'STM32, ESP32, Arduino and RTOS firmware engineering',
      'End-to-end PCB fabrication and assembly support',
      'Hardware design review and consulting',
    ],
    subServices: [
      { slug: 'product-design', title: 'Electronics Product Design', desc: 'Concept to prototype architecture, BOM, and circuit design.' },
      { slug: 'pcb-design', title: 'PCB Design Services', desc: 'Schematic capture, multi-layer layout, and high-speed routing.' },
      { slug: 'embedded-systems', title: 'Embedded Systems & Firmware', desc: 'STM32, ESP32, FreeRTOS, and real-time device drivers.' },
      { slug: 'end-to-end-pcb', title: 'End-to-End PCB Development', desc: 'Fabrication support, assembly management, testing, and QA.' },
      { slug: 'consulting', title: 'Hardware Consulting Services', desc: 'Design review, signal integrity, and PCB cost optimization.' },
    ],
    industries: ['IoT & Smart Devices', 'Industrial Automation', 'Consumer Electronics', 'Healthcare Devices', 'Automotive'],
  },

  'hardware/product-design': {
    title: 'Electronics Product Design',
    tagline: 'Architecting Hardware for Scalable Manufacturing',
    category: 'Hardware',
    parentSlug: 'hardware',
    parentTitle: 'Hardware Design & Embedded Systems',
    heroBg: 'bg-gradient-to-br from-teal-950 via-slate-900 to-black text-white',
    description: 'From initial requirements to proven hardware prototypes. We evaluate components, perform circuit simulations, and design electronic products with DFM (Design for Manufacturing) standards.',
    features: [
      'Circuit Design & Simulation: SPICE simulation and worst-case circuit analysis',
      'Product Architecture: Power budgeting, microcontroller selection, and sensor matrix',
      'Component Selection & BOM Optimization: Sourcing reliable, active components to avoid obsolescence',
      'Prototype Development: Rapid breadboarding, bench testing, and functional proof-of-concept',
    ],
    deliverables: [
      'Complete schematics with design verification reports',
      'Consolidated Bill of Materials (BOM) with manufacturer part numbers',
      'Power tree and thermal distribution analysis',
      'Functional hardware prototype boards',
    ],
    industries: ['Consumer Electronics', 'Industrial Monitoring', 'Medical Devices', 'Smart Agriculture'],
  },

  'hardware/pcb-design': {
    title: 'PCB Design Services',
    tagline: 'Precision Multi-Layer & High-Speed PCB Layout',
    category: 'Hardware',
    parentSlug: 'hardware',
    parentTitle: 'Hardware Design & Embedded Systems',
    heroBg: 'bg-gradient-to-br from-emerald-950 via-slate-900 to-black text-white',
    description: 'Professional PCB layout services in KiCad and Altium. We handle 2-layer to 8+ layer multi-layer boards, RF impedance matching, high-speed differential routing, and design rule checks (DRC).',
    features: [
      'Schematic Capture & Component Symbol Creation',
      'Multi-Layer PCB Layout (2-layer to 8+ layer boards)',
      'High-Speed Routing: Controlled impedance, length matching, and differential pairs',
      'RF PCB Design: Antenna matching networks, ground stitching, and EMI shielding',
      'Design Rule Checks (DRC) and Design for Assembly (DFA) verification',
    ],
    deliverables: [
      'Production-ready Gerber RS-274X files and NC drill files',
      'IPC-compliant footprint libraries and 3D STEP models for mechanical CAD',
      'Centroid / Pick-and-Place (CPL) and BOM assembly files',
      'Fabrication and assembly technical drawings',
    ],
    industries: ['Wireless IoT', 'Robotics & Motor Control', 'Power Electronics', 'Telematics'],
  },

  'hardware/embedded-systems': {
    title: 'Embedded Systems & Firmware',
    tagline: 'Deterministic, Real-Time Microcontroller Code',
    category: 'Hardware',
    parentSlug: 'hardware',
    parentTitle: 'Hardware Design & Embedded Systems',
    heroBg: 'bg-gradient-to-br from-green-950 via-slate-900 to-black text-white',
    description: 'Low-level embedded C and C++ development for microcontrollers and SoCs. We develop reliable, real-time operating system (RTOS) firmware, sensor drivers, and secure communication stacks.',
    features: [
      'STM32 Development: ARM Cortex-M0/M3/M4/M7 firmware engineering',
      'ESP32 Development: Wi-Fi, BLE, mesh networking, and ESP-IDF architectures',
      'Arduino & Microchip Solutions: Rapid prototyping and cost-sensitive controllers',
      'RTOS Architecture: FreeRTOS task scheduling, queues, semaphores, and memory safety',
      'Firmware Drivers: Custom drivers for I2C, SPI, UART, CAN bus, and ADC peripherals',
    ],
    deliverables: [
      'Clean, modular, well-documented C/C++ source code repositories',
      'Secure bootloader and Over-The-Air (OTA) firmware upgrade pipelines',
      'Memory optimization and low-power sleep state implementations',
      'Hardware-in-the-loop (HIL) test suites and validation logs',
    ],
    industries: ['Connected Hardware', 'Industrial Telemetry', 'Smart Energy', 'Automation'],
  },

  'hardware/end-to-end-pcb': {
    title: 'End-to-End PCB Development',
    tagline: 'From Concept to Assembled & Tested Boards',
    category: 'Hardware',
    parentSlug: 'hardware',
    parentTitle: 'Hardware Design & Embedded Systems',
    heroBg: 'bg-gradient-to-br from-teal-950 via-neutral-900 to-black text-white',
    description: 'We manage the entire lifecycle of your electronic boards: requirements analysis, schematic capture, PCB layout, Gerber generation, component sourcing, fabrication liaison, PCB assembly (PCBA), and testing.',
    features: [
      'Requirement Analysis and System Specification',
      'Schematic Capture & Component Sourcing Liaison',
      'PCB Layout and Gerber Data Package Generation',
      'Fabrication Support: PCB layer stackup and surface finish selection (ENIG / HASL)',
      'Assembly Support: SMT stenciling, reflow soldering management, and component placement',
      'Testing & Validation: Board bring-up, power rail verification, and functional validation',
    ],
    deliverables: [
      'Fully assembled, tested, and validated PCBA boards',
      'Quality inspection reports and test point logs',
      'Complete manufacturing release package',
    ],
    industries: ['Hardware Startups', 'R&D Labs', 'Industrial Equipment', 'IoT Devices'],
  },

  'hardware/consulting': {
    title: 'Hardware Consulting Services',
    tagline: 'Expert Design Review & Engineering Optimization',
    category: 'Hardware',
    parentSlug: 'hardware',
    parentTitle: 'Hardware Design & Embedded Systems',
    heroBg: 'bg-gradient-to-br from-slate-950 via-neutral-900 to-black text-white',
    description: 'Independent engineering consultation on electronic architectures, schematic review, PCB troubleshooting, signal integrity analysis, and unit cost optimization before committing to production.',
    features: [
      'Hardware Design Review: Identify schematic errors, power routing flaws, and thermal issues',
      'PCB Optimization: Reduce layer counts, optimize board area, and minimize manufacturing costs',
      'Embedded Consulting: Review RTOS thread safety, latency, and peripheral bottlenecks',
      'Product Development Guidance: Navigating compliance, certifications, and manufacturing partners',
    ],
    deliverables: [
      'Detailed Design Review Audit Document with prioritized action items',
      'Cost reduction suggestions and component alternate matrices',
      'Signal integrity and EMC reduction recommendations',
    ],
    industries: ['Electronic Manufacturers', 'Startups with Prototypes', 'Academic Labs'],
  },

  // ── Main Category 3: Training ──
  'training': {
    title: 'Workshops, Training & DIY Kits',
    tagline: 'Learn by Building',
    category: 'Training',
    parentSlug: null,
    heroBg: 'bg-gradient-to-br from-amber-950 via-slate-900 to-black text-white',
    description: 'We believe engineering is best learned through practical experience. CoreForge conducts hands-on workshops, industrial training, and technical bootcamps that prepare students and professionals for real-world engineering challenges.',
    features: [
      'Hands-on embedded systems and hardware design bootcamps',
      'Full-stack web and mobile application development programs',
      'Corporate and college faculty development programs (FDPs)',
      'DIY electronics kits with comprehensive video tutorials',
      'Mentorship for capstone, final-year, and competition projects',
    ],
    subServices: [
      { slug: 'embedded-training', title: 'Embedded Systems Training', desc: 'Embedded C, STM32, ESP32, Arduino, and IoT bootcamps.' },
      { slug: 'hardware-courses', title: 'Hardware Design Courses', desc: 'PCB design in KiCad, analog/digital electronics, circuit layout.' },
      { slug: 'software-programs', title: 'Software Development Programs', desc: 'Full-stack web development, mobile apps, and databases.' },
      { slug: 'workshops', title: 'Corporate & College Workshops', desc: 'FDPs, student bootcamps, industrial training, and internships.' },
      { slug: 'diy-kits', title: 'DIY Electronics Kits', desc: 'Beginner kits, IoT learning packs, and robotics modules.' },
      { slug: 'academic-projects', title: 'Academic & Competition Projects', desc: 'Mentorship for final year projects and research prototypes.' },
    ],
    industries: ['Engineering Colleges', 'Universities', 'Corporate Engineering Teams', 'Student Makers', 'Polytechnics'],
  },

  'training/embedded-training': {
    title: 'Embedded Systems Training',
    tagline: 'Master Real-Time Embedded C & Microcontrollers',
    category: 'Training',
    parentSlug: 'training',
    parentTitle: 'Workshops, Training & DIY Kits',
    heroBg: 'bg-gradient-to-br from-orange-950 via-slate-900 to-black text-white',
    description: 'Comprehensive practical training programs in Embedded C programming, microcontroller register-level architecture, STM32 HAL, ESP32 Wi-Fi/BLE IoT stacks, and FreeRTOS task management.',
    features: [
      'Embedded C: Memory models, bit manipulation, pointers, and register programming',
      'STM32 Microcontrollers: ARM Cortex-M architecture, timers, interrupts, ADC, and DMA',
      'ESP32 & IoT: MQTT protocol, HTTP clients, BLE beacons, and cloud data logging',
      'Arduino Solutions: Sensor interfacing, motor drivers, and rapid prototyping',
      'FreeRTOS: Task creation, priority scheduling, queues, and mutexes',
    ],
    deliverables: [
      'Hands-on hardware kits provided for every participant',
      'Real-world project code repository with build configurations',
      'CoreForge Professional Certificate of Completion',
    ],
    industries: ['Engineering Students', 'Junior Hardware Engineers', 'Robotics Enthusiasts'],
  },

  'training/hardware-courses': {
    title: 'Hardware & PCB Design Courses',
    tagline: 'Learn Circuit Design & Multi-Layer PCB Layout',
    category: 'Training',
    parentSlug: 'training',
    parentTitle: 'Workshops, Training & DIY Kits',
    heroBg: 'bg-gradient-to-br from-amber-950 via-slate-900 to-black text-white',
    description: 'Hands-on courses in schematic design, analog and digital circuit analysis, component selection, and multi-layer PCB layout using industry-standard tools like KiCad and Altium.',
    features: [
      'PCB Design in KiCad & Altium: Schematic capture to multi-layer routing',
      'Analog Electronics: Op-amps, filters, voltage regulators, and sensor signal conditioning',
      'Digital Electronics: Logic gates, microcontrollers, communication buses (I2C / SPI)',
      'Design for Manufacturing (DFM): Generating Gerbers, drill files, and pick-and-place files',
    ],
    deliverables: [
      'Design your own custom PCB fabricated and delivered to you',
      'Comprehensive design rule templates and footprint libraries',
      'Design verification and debugging sessions',
    ],
    industries: ['ECE / EEE Students', 'Embedded Engineers', 'Hardware Startups'],
  },

  'training/software-programs': {
    title: 'Software Development Programs',
    tagline: 'Full-Stack Web & Mobile Application Engineering',
    category: 'Training',
    parentSlug: 'training',
    parentTitle: 'Workshops, Training & DIY Kits',
    heroBg: 'bg-gradient-to-br from-blue-950 via-slate-900 to-black text-white',
    description: 'Intensive, project-driven software development training covering modern frontend engineering with React, backend development with Node.js and Python, databases, and mobile app creation.',
    features: [
      'Full-Stack Web Development: HTML5, CSS3, JavaScript ES6+, React, and Tailwind',
      'Backend Architecture: Node.js, Express, RESTful APIs, and database modeling',
      'Mobile App Development: Cross-platform development with React Native',
      'Version Control & Deployment: Git, GitHub workflows, CI/CD, and cloud hosting',
    ],
    deliverables: [
      'Build and deploy 3 production-grade portfolio applications',
      'Live code review and technical interview preparation',
      'Industry-standard GitHub portfolio audit',
    ],
    industries: ['Computer Science Students', 'Career Switchers', 'Tech Enthusiasts'],
  },

  'training/workshops': {
    title: 'Corporate & College Workshops',
    tagline: 'Bridging Industry Standards with Hands-On Education',
    category: 'Training',
    parentSlug: 'training',
    parentTitle: 'Workshops, Training & DIY Kits',
    heroBg: 'bg-gradient-to-br from-purple-950 via-slate-900 to-black text-white',
    description: 'Customized workshops for universities, colleges, and corporate R&D teams. We run Faculty Development Programs (FDPs), technical hackathons, and corporate upskilling sessions.',
    features: [
      'Faculty Development Programs (FDPs): Emerging tech curriculum training for educators',
      'Industrial Workshops: 2-day to 5-day hands-on bootcamps for student cohorts',
      'Student Bootcamps: Practical engineering sprints with hardware kits',
      'Structured Internship Programs: 3-month project internships with mentor review',
    ],
    deliverables: [
      'Custom curriculum aligned with institution goals',
      'All hardware kits, components, and documentation supplied',
      'Performance evaluation and digital credentials for participants',
    ],
    industries: ['Engineering Institutions', 'Polytechnics', 'Corporate Engineering Teams'],
  },

  'training/diy-kits': {
    title: 'DIY Electronics & Robotics Kits',
    tagline: 'Learn by Building with Pre-Packaged Hardware Packs',
    category: 'Training',
    parentSlug: 'training',
    parentTitle: 'Workshops, Training & DIY Kits',
    heroBg: 'bg-gradient-to-br from-amber-950 via-slate-900 to-black text-white',
    description: 'Carefully engineered DIY kits containing genuine components, custom PCB shields, step-by-step schematics, sample firmware, and video tutorials for independent learning.',
    features: [
      'Beginner Electronics Kits: Fundamental circuit building and sensor experiments',
      'IoT Starter Kits: ESP32 Wi-Fi boards, environmental sensors, and cloud dashboard guides',
      'Robotics Kits: Motor controllers, chassis, ultrasonic obstacles, and line following',
      'Embedded Learning Kits: STM32 breakout boards, display shields, and debugging cables',
    ],
    deliverables: [
      'High-quality genuine hardware components and custom boards',
      'Detailed visual instruction manual and video guides',
      'Open-source code repositories with modular examples',
    ],
    industries: ['Students', 'STEM Schools', 'Makerspaces', 'Self-Learners'],
  },

  'training/academic-projects': {
    title: 'Academic & Competition Projects',
    tagline: 'Mentorship for Capstone, Final-Year & Research Prototypes',
    category: 'Training',
    parentSlug: 'training',
    parentTitle: 'Workshops, Training & DIY Kits',
    heroBg: 'bg-gradient-to-br from-slate-950 via-neutral-900 to-black text-white',
    description: 'Professional engineering guidance for engineering final year projects, technical hackathons, national competitions, and research prototypes. We help students turn ideas into functioning systems.',
    features: [
      'Final Year Capstone Projects: Hardware, embedded, and full-stack software systems',
      'Competition Prototypes: High-reliability systems built for hackathons and design challenges',
      'Research Prototypes: Experimental sensor systems, telemetry logging, and prototype validation',
      'Technical Documentation Support: Block diagrams, schematic explanations, and testing logs',
    ],
    deliverables: [
      'Fully functioning hardware/software prototype system',
      'Complete circuit schematics, source code, and bill of materials',
      'Technical guidance on project demonstration and Q&A defense',
    ],
    industries: ['Final Year Engineering Students', 'Hackathon Teams', 'Research Scholars'],
  },
}
